### ISSUE TITLE
Where is vimrc file?

### ISSUE THREAD

**Issue by taharathussain** [erichiller/cmder#1]
I wanted to change some keybindings which can be done through vimrc file. Where is the vimrc file for Vim in cmder. (Note that CMDER full edition have a VIM by default, so I don't wanna pollute my system by installing another VIM, but wanna change setting for the one included in CMDER)

There two vimrc files, one file says in the comments to copy that file to C:/$VIM/_vimrc which I did, but it didn't reflect settings in the Vim editor, then I changed the settings in the other vimrc file too, but it didn't make any difference either.

Please help me.

**Comment by erichiller** [comment]
I can try to give you a hand here. Keep in mind that this is a _very_ modified fork of the original cmder project which can be found [here](https://github.com/cmderdev/cmder)
While I do not update this project anymore, I have moved onto the similarly purposed [omega](https://github.com/erichiller/omega) and this 
 [.vimrc probably contains exactly what you are looking for](https://github.com/erichiller/omega/blob/master/config/omega.vimrc).

I hope that this helps.
